            # ("Abrir Imagem", def_0_abrir_imagem),
            # ("Split and Merge", def_1_split_and_merge),
            # ("Separar Canais RGB", def_2_separar_canais_RGB),
            # ("RGB para HSV", def_3_convert_RGB_to_HSV),
            # ("HSV para RGB", def_4_convert_HSV_to_RGB),
            
            # ("Espaço de Cores YCrCb", def_5_espaco_de_cores_YCrCb),
            # ("Espaço de Cor LAB", def_6_espaco_de_cor_LAB),
            # ("Tons de Cinza", def_7_convertendo_em_tons_de_cinza),
            # ("Converter Modelos de Cor", def_8_converter_modelos_cor),
            # ("Propriedades da Imagem", def_9_propriedades_da_imagem),
            # ("Pegar Cor de um Pixel", def_10_pegar_cor_de_um_pixel),
            # ("Modificar Cor de um Pixel", def_11_modificar_cor_de_um_pixel),
            # ("Região de Interesse", def_12_regiao_de_interesse),
            # ("Redimensionar Imagem", def_13_redimensionar_imagem),
            # ("Ajuste de Brilho", def_14_ajuste_de_brilho),
            # ("Ajuste de Contraste", def_15_ajuste_de_contraste),
            # ("Inverter Cores", def_16_inverter_cores),
            # ("Negativo da Imagem", def_17_negativo_da_imagem),
            # ("Adicionar Imagens", def_18_adicionar_imagens),
            # ("Subtrair Imagens", def_19_subtrair_imagens),
            # ("Multiplicar Imagens", def_20_multiplicar_imagens),
            # ("Dividir Imagens", def_21_dividir_imagens),
            # ("Média de Duas Imagens", def_22_media_de_duas_imagens),
            # ("Filtro Média", def_23_filtro_media),
            # ("Filtro Mediana", def_24_filtro_mediana),
            # ("Suavizar Imagem", def_25_suavizar_imagem),
            # ("Realçar Imagem", def_26_realcar_imagem),
            # ("Calcular Histograma", def_27_calcular_histograma),
            # ("Histograma Colorido", def_28_calcular_histograma_colorido),
            # ("Binarizar Imagem", def_29_binarizar_imagem),
            # ("Equalizar Histograma", def_30_equalizar_histograma),
            # ("Quantizar Histograma", def_31_quantizar_histograma),
            # ("Split Histograma", def_32_split_histograma),
            # ("Stretching Histograma", def_33_stretching_histograma),
            # ("Erosão", def_34_erosao),
            # ("Dilatação", def_35_dilatacao),
            # ("Abertura", def_36_abertura),
            # ("Fechamento", def_37_fechamento),
            # ("Abertura/Fechamento Tons de Cinza", def_38_abertura_fechamento_tons_cinza),
            # ("Gradiente Morfológico", def_39_gradiente_morfologico),
            # ("Top Hat", def_40_top_hat),
            # ("Eliminação de Ruídos", def_41_eliminacao_ruidos),
